param(
    [switch]$SkipInstall,
    [switch]$ReleasePackage
)

# EternalRichPresence build script — produces a portable .exe and optional release package

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $RepoRoot

$AppName = "EternalRichPresence"
$ExeName = "$AppName.exe"
$Version = (python -c "from app_info import APP_VERSION; print(APP_VERSION)" | Out-String).Trim()
if (-not $Version) {
    throw "Could not determine app version from app_info.py"
}

$ReleaseName = "$AppName-v$Version-windows"
$ReleaseRoot = Join-Path $RepoRoot "release"
$ArtifactDir = Join-Path $ReleaseRoot $ReleaseName
$ZipPath = Join-Path $ReleaseRoot "$ReleaseName.zip"
$ChecksumsPath = Join-Path $ReleaseRoot "$ReleaseName-checksums.txt"
$ReleaseBodyPath = Join-Path $ReleaseRoot "$ReleaseName-release-body.md"
$QuickStartPath = Join-Path $ArtifactDir "README-QuickStart.txt"

if (-not $SkipInstall) {
    Write-Host "Installing / updating dependencies..." -ForegroundColor Cyan
    pip install -r requirements.txt pyinstaller
}

if (-not (Test-Path ".\Apple_Music_Icon.png")) {
    throw "Apple_Music_Icon.png is missing from the project root."
}

Write-Host "Regenerating version_info.txt from app_info.py..." -ForegroundColor Cyan
$VersionFile = (python -c "from app_info import APP_VERSION_FILE; print(APP_VERSION_FILE)" | Out-String).Trim()
$AppNameMeta = (python -c "from app_info import APP_NAME; print(APP_NAME)" | Out-String).Trim()
$Author      = (python -c "from app_info import APP_AUTHOR; print(APP_AUTHOR)" | Out-String).Trim()
if (-not $VersionFile) {
    throw "Could not determine APP_VERSION_FILE from app_info.py"
}
$VerTuple = ($VersionFile -split '\.') -join ', '
$VersionInfoBody = @"
# Auto-generated by build.ps1 from app_info.py (APP_VERSION_FILE). Do not edit by
# hand — manual changes are overwritten on the next build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=($VerTuple),
    prodvers=($VerTuple),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName', u'$Author'),
            StringStruct(u'FileDescription', u'EternalRichPresence — Discord Rich Presence for Apple Music & Spotify'),
            StringStruct(u'FileVersion', u'$VersionFile'),
            StringStruct(u'InternalName', u'$AppNameMeta'),
            StringStruct(u'LegalCopyright', u'Copyright (C) 2026 Ali Younes (@whoisaldo). Licensed under GPL-3.0-or-later.'),
            StringStruct(u'OriginalFilename', u'$AppNameMeta.exe'),
            StringStruct(u'ProductName', u'$AppNameMeta'),
            StringStruct(u'ProductVersion', u'$VersionFile'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"@
Set-Content -Path (Join-Path $RepoRoot "version_info.txt") -Value $VersionInfoBody -Encoding UTF8

Write-Host "Cleaning previous build outputs..." -ForegroundColor Cyan
Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
Remove-Item -Force "$AppName.spec" -ErrorAction SilentlyContinue
Remove-Item -Force $ExeName -ErrorAction SilentlyContinue

Write-Host "Building executable..." -ForegroundColor Cyan
python -m PyInstaller `
    --onefile `
    --noconsole `
    --icon=Apple_Music_Icon.png `
    --name="$AppName" `
    --version-file=version_info.txt `
    --add-data "Apple_Music_Icon.png;." `
    --hidden-import providers `
    --hidden-import providers.base `
    --hidden-import providers.apple_music `
    --hidden-import providers.spotify `
    --hidden-import manager `
    --hidden-import presence `
    --hidden-import utils `
    --hidden-import logger `
    --hidden-import setup_gui `
    --hidden-import discord_events `
    --hidden-import pystray `
    --hidden-import PIL `
    --hidden-import PIL.Image `
    --hidden-import pypresence `
    --hidden-import winrt `
    --hidden-import winrt.windows.media.control `
    --hidden-import winrt.windows.storage.streams `
    --hidden-import winrt.windows.foundation `
    --collect-all winrt `
    --collect-all pystray `
    main.py

Write-Host "Moving executable to project root..." -ForegroundColor Cyan
Move-Item -Force "dist\$ExeName" ".\$ExeName"

if ($ReleasePackage) {
    Write-Host "Preparing GitHub release package..." -ForegroundColor Cyan
    Remove-Item -Recurse -Force $ReleaseRoot -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Path $ArtifactDir -Force | Out-Null

    Copy-Item ".\$ExeName" -Destination (Join-Path $ArtifactDir $ExeName)

    $QuickStartBody = @(
        "EternalRichPresence v$Version",
        "",
        "Quick start:",
        "1. Download EternalRichPresence.exe",
        "2. Run it",
        "3. The app is preconfigured for Discord and will live in your system tray",
        "4. Optional: open the Dev menu later if you want to configure Spotify",
        "",
        "If Discord or Listen Along ever needs attention:",
        "- Use Repair Listen Along from the tray",
        "- Use Reconnect to Discord from the tray",
        "- Use Dev > Open Log File for support logs"
    )
    Set-Content -Path $QuickStartPath -Value $QuickStartBody -Encoding UTF8

    if (Test-Path $ZipPath) {
        Remove-Item -Force $ZipPath
    }
    Compress-Archive -Path (Join-Path $ArtifactDir "*") -DestinationPath $ZipPath -Force

    $ExeHash = Get-FileHash ".\$ExeName" -Algorithm SHA256
    $ZipHash = Get-FileHash $ZipPath -Algorithm SHA256
    @(
        "$($ExeHash.Hash) *$ExeName"
        "$($ZipHash.Hash) *$(Split-Path $ZipPath -Leaf)"
    ) | Set-Content -Path $ChecksumsPath -Encoding ASCII

    $ReleaseBody = @(
        "## Downloads",
        "- $ExeName",
        "- $(Split-Path $ZipPath -Leaf)",
        "- $(Split-Path $ChecksumsPath -Leaf)",
        "",
        "## What's new",
        "- Polished first-run experience with the official Discord app preconfigured",
        "- Cleaner tray UX with important actions up front and advanced tools moved into Dev",
        "- Improved error handling, reconnect flows, and release readiness",
        "",
        "## Install",
        "1. Download $ExeName",
        "2. Run it",
        "3. Play music in Apple Music or Spotify",
        "",
        "## SHA256",
        "",
        "$($ExeHash.Hash)  $ExeName",
        "$($ZipHash.Hash)  $(Split-Path $ZipPath -Leaf)"
    )
    Set-Content -Path $ReleaseBodyPath -Value $ReleaseBody -Encoding UTF8
}

Write-Host "Cleaning up build artifacts..." -ForegroundColor Cyan
Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
Remove-Item -Force "$AppName.spec" -ErrorAction SilentlyContinue
Remove-Item -Recurse -Force __pycache__ -ErrorAction SilentlyContinue

Write-Host "" -ForegroundColor Green
Write-Host "Done! $ExeName is ready." -ForegroundColor Green
if ($ReleasePackage) {
    Write-Host "Release outputs:" -ForegroundColor Green
    Write-Host "  $ZipPath"
    Write-Host "  $ChecksumsPath"
    Write-Host "  $ReleaseBodyPath"
}
